SELECT 
    CITY_ID,
    DATE(DATE_TIME) AS DATE,
    AVG(TEMP) AS AVG_TEMP,
    AVG(FEELS_LIKE) AS AVG_FEELS_LIKE,
    AVG(PRESSURE) AS AVG_PRESSURE,
    AVG(HUMIDITY) AS AVG_HUMIDITY,
    AVG(WIND_SPEED) AS AVG_WIND_SPEED,
    AVG(CLOUD_COVERAGE) AS AVG_CLOUD_COVERAGE
FROM 
    {{ source('raw_data', 'weather_fact_table') }}
GROUP BY 
    CITY_ID, DATE
